environment:
  global:
    CMD_IN_ENV: "cmd /E:ON /V:ON /C obvci_appveyor_python_build_env.cmd"
    TARGET_ARCH: "x64"

  matrix:
    - CONDA_PY: 3.5
      MINICONDA: C:\Miniconda35-x64
    - CONDA_PY: 3.6
      MINICONDA: C:\Miniconda36-x64

init:
  - "ECHO %CONDA_PY% %MINICONDA%"
  - "set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%PATH%"
  - conda config --set always_yes yes --set changeps1 no

install:
  - powershell -Command "(New-Object Net.WebClient).DownloadFile('https://raw.githubusercontent.com/pelson/Obvious-CI/master/scripts/obvci_appveyor_python_build_env.cmd', 'obvci_appveyor_python_build_env.cmd')"
  - "conda create -q -n testenv python=%CONDA_PY% h5py xarray pytables pytest pytest-runner cython"
  - "conda install --yes -n testenv -c conda-forge ase periodictable vtk"
  - activate testenv

build: off

test_script:
  - "%CMD_IN_ENV% python setup.py test"
