language: python

python:
  - "3.5"
  - "3.6"

before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no

install:
  - conda create -q -n testenv python=$TRAVIS_PYTHON_VERSION h5py xarray pytables pytest-cov pytest-runner cython flake8
  - conda install --yes -n testenv -c conda-forge ase periodictable vtk codecov
  - conda install --yes -n testenv -c diffpy/label/dev diffpy.structure
  - source activate testenv

script:
  - python setup.py test --addopts --cov=javelin
  - flake8

after_success:
  - codecov
