language: python

python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"

install:
  - pip install flake8 ase pytest-cov codecov Cython
  - pip install h5py

script:
  - py.test --cov=javelin --doctest-modules javelin tests
  - flake8

after_success:
  - codecov
