name: testenv
channels:
- defaults
- conda-forge
- diffpy/label/dev
dependencies:
- python=3.5
- cython=0.23
- h5py=2.5
- numpy=1.10
- pandas=0.17
- pytables=3.2
- xarray=0.7
- ase=3.14
- periodictable=1.4
- vtk=7.0
- diffpy.structure=3.0
- pytest-cov
- pytest-runner
- codecov
- flake8
